### ISSUE TITLE
[Question] CefInstance View Texture is not generated

### ISSUE THREAD

**Issue by gtk2k** [coderiekelt/UnityCefSharp#10]
I'm trying UnityCefSharp, but after completing the steps and running it in Unity, I've confirmed that a GUID GameObject with a CefInstance attached is generated. I also confirmed that CevServer was messed up and UDP 9002 was listening.
However, the View Texture of CefInstance is not generated.
Is there anything else I need?
(For example, Cef body is required)

**Comment by coderiekelt** [comment]
Hi,

I've managed to reproduce this issue, and am currently looking into fixing it.

I do apologize for the inconvenience, and hope to have it resolved for you soon!

**Comment by gtk2k** [comment]
Thanx!

**Comment by coderiekelt** [comment]
I pushed a quick fix for this issue, and will refactor some parts of `CefClient` in the next few days to address this issue in a more elegant way.

Basically what was going wrong is that `CefClient` tried to send `CefCreateInstanceEvent` to the server before it's ready, causing the `CefInstance` to get stuck in an initializing state, while the server would never respond back with a `CefInstanceCreatedEvent`.

I recommend pulling and using `Rebuild Solution`, then you can change the condition in ChromiumGUI.cs on line 39 to
```cs
if (!_initialized && InstanceManager.Instance.IsReady()) {
```

Then it should wait until CefClient is connected to CefServer before sending out any events.

If you run into any more problems feel free to let me know!

**Comment by gtk2k** [comment]
Thanx for quick fix!
But, now the Cefserver.exe process starts and ends in a few seconds, and the View Texture remains unchanged.

**Comment by coderiekelt** [comment]
That's weird, I have updated `ChromiumManager.cs` can you update that file in your project, uncheck `Use Internal Process`, and then start CefServer from Visual Studio and check what happens?

**Comment by gtk2k** [comment]
Sorry!
I forgot to update the UnityScripts folder!
Updating the UnityScripts folder to view the browser!

Please ask questions by adding.
Isn't it possible to display a browser on 3D space?

**Comment by coderiekelt** [comment]
It is possible to use the browser in 3D space, I'm still working on a sample script for that but basically what you have to do is create a new `MonoBehaviour`, add it to an object with a `MeshRenderer` and set the material for that to `CefInstance.ViewTexture`.

I hope to have a sample for that ready soon, but it shouldn't be too hard to implement that.

**Comment by gtk2k** [comment]
Thanx!
I will solve this problem, so I will be closed.
